### ISSUE TITLE
Panics with "attempt to subtract with overflow"

### ISSUE THREAD

**Issue by msakrejda** [rowan-sl/trifit#2]
```
maciek@whimbrel:/tmp/trifit$ target/debug/trifit --image-size 1200 --tri-size 15 --iterations 50 --shift 0.5 --format image --scoring avg-with-shape-weight lake.jpg triangle-lake.jpg
 INFO  trifit > Initialized
Original: (4032, 3024), new: (1200, 900)
Iteration progress                                [--------------------------------------------------------------------------------------------------------------------------------------------------]   0%
thread '<unnamed>' panicked at 'attempt to subtract with overflow', src/scoring/mod.rs:299:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
 TRACE mio::poll > registering with poller
 TRACE mio::poll > registering with poller
 TRACE mio::poll > registering with poller
 TRACE mio::poll > registering with poller
 TRACE mio::poll > registering with poller
 INFO  winit::platform_impl::platform::x11::window > Guessed window scale factor: 2
 DEBUG winit::platform_impl::platform::x11::window > Calculated physical dimensions: 2560x2560
thread 'main' panicked at 'attempt to subtract with overflow', src/scoring/mod.rs:299:25
 TRACE mio::poll                                   > deregistering event source from poller
```

**Comment by msakrejda** [comment]
On the same image but with `--image-size 800` and a release build, it makes some progress here with the latest changes, but then panics with

```
Iteration progress                                [====================================================================================================----------------------------------------------]  69%
thread '<unnamed>' panicked at 'assertion failed: 0.0 <= squareness && squareness <= 100.0', src/scoring/mod.rs:318:13
stack backtrace:
   0: rust_begin_unwind
             at /rustc/c0941dfb5a7d07ef2d70cc54d319669d9d6f6c01/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/c0941dfb5a7d07ef2d70cc54d319669d9d6f6c01/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/c0941dfb5a7d07ef2d70cc54d319669d9d6f6c01/library/core/src/panicking.rs:48:5
   3: trifit::scoring::score
   4: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::fold
   5: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
   6: trifit::scoring::score_for_group
   7: core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &mut F>::call_once
   8: <core::iter::adapters::map::Map<I,F> as core::iter::traits::iterator::Iterator>::next
   9: <alloc::vec::Vec<T> as alloc::vec::spec_from_iter::SpecFromIter<T,I>>::from_iter
  10: trifit::optimize_one
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Procesing thread exiting
thread 'main' panicked at 'Box<dyn Any>', src/main.rs:405:45
stack backtrace:
   0: std::panicking::begin_panic
   1: std::panic::panic_any
   2: trifit::main::{{closure}}
   3: std::thread::local::LocalKey<T>::with
   4: tokio::park::thread::CachedParkThread::block_on
   5: tokio::runtime::thread_pool::ThreadPool::block_on
   6: tokio::runtime::Runtime::block_on
   7: trifit::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
 TRACE mio::poll                                   > deregistering event source from poller
```

**Comment by ashsystems** [comment]
this shouldn't be an issue anymore, (removed the assertion, will look into it later when I have more time). I really should just re-write a large part of this since there are so many hidden issues. leaving open for now to remind myself
